Dating/Controllers/PhotosController.cs
using AutoMapper;
using CloudinaryDotNet;
using CloudinaryDotNet.Actions;
using Dating.Data.Repositories;
using Dating.Helpers;
using Dating.Models;
using Dating.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;

namespace Dating.Controllers
{

    public class PhotosController : Controller
    {
        private readonly IDatingRepository _repo;
        private readonly IMapper _mapper;
        private readonly IOptions<CloudinarySettings> _cloudinaryOptions;
        private readonly Cloudinary _cloudinary;
        public PhotosController(IDatingRepository repo, IMapper mapper,
            IOptions<CloudinarySettings> cloudinaryOptions)
        {
            _repo = repo;
            _mapper = mapper;
            _cloudinaryOptions = cloudinaryOptions;

            Account account = new Account(
                cloudinaryOptions.Value.CloudName,
            cloudinaryOptions.Value.ApiKey,
            cloudinaryOptions.Value.ApiSecret
            );
            _cloudinary = new Cloudinary(account);
        }

        private bool TrueUser(string userId)
        {
           
            var currentuserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            if (currentuserId != userId)
            {
                return false;
            }
            return true;
        }
        public async Task<IActionResult> PhotosList(string userId)
        {
            if (userId == null)
            {
                return NotFound();
            }
            if (!TrueUser(userId))
            {
                return StatusCode(401);
            }
            ViewBag.UserId = userId;
            var photos= await _repo.GetPhotos(userId);
            //var photosToReturn = _mapper.Map<IEnumerable<PhotosListViewModel>>(photos);
            return PartialView("PhotosList", new PhotosModel(_cloudinary, photos));
        }
        public ActionResult UploadDirectly(string userId)
        {
            if (userId == null)
            {
                return NotFound();
            }
            if (!TrueUser(userId))
            {
                return StatusCode(401);
            }
            var model = new DictionaryModel(_cloudinary, new Dictionary<string, string>()
            { { "unsigned", "false" } });

            return PartialView("UploadDirectly", model);
        }

        public ActionResult UploadDirectlyUnsigned(string userId)
        {
            if (userId == null)
            {
                return NotFound();
            }
            if (!TrueUser(userId))
            {
                return StatusCode(401);
            }
            var preset = "sample_" + _cloudinary.Api.SignParameters(new SortedDictionary<string, object>()
            { { "api_key", _cloudinary.Api.Account.ApiKey } })
                .Substring(0, 10);
            var result = _cloudinary.CreateUploadPreset(new UploadPresetParams()
            { Name = preset, Unsigned = true, Folder = "preset_folder" }
            );

            var model = new DictionaryModel(_cloudinary, new Dictionary<string, string>()
            { { "unsigned", "true" },
                { "preset", preset } });

            return PartialView("UploadDirectly", model);
        }

        [HttpPost]
        public void UploadDirect(string userId)
        {

            //var headers = HttpContext.Request.Headers;

            //string content = null;
            //using (StreamReader reader = new StreamReader(HttpContext.Request.Form.Files.ToString()))
            //{
            //    content = reader.ReadToEnd();
            //}
            //if (String.IsNullOrEmpty(content)) return;

            //Dictionary<string, string> results = new Dictionary<string, string>();

            //string[] pairs = content.Split(new char[] { '&' }, StringSplitOptions.RemoveEmptyEntries);
            //foreach (var pair in pairs)
            //{
            //    string[] splittedPair = pair.Split('=');

            //    if (splittedPair[0].StartsWith("faces"))
            //        continue;

            //    results.Add(splittedPair[0], splittedPair[1]);
            //}
            var files = HttpContext.Request.Form.Files;
            var results = new ImageUploadResult();
            foreach (var file in files)
            {
                if (file != null && file.Length > 0)
                {
                    using (var stream = file.OpenReadStream())
                    {
                        var uploadParams = new ImageUploadParams()
                        {
                            File = new FileDescription(file.Name, stream)
                        };
                        results = _cloudinary.Upload(uploadParams);
                    }

                    Photo p = new Photo()
                    {
                       
                        CreatedAt = results.CreatedAt,
                        Format = results.Format,
                        Height = results.Height,
                        
                        PublicId = results.PublicId,
                        ResourceType = results.ResourceType,
                        SecureUrl = results.SecureUri.ToString(),
                        Signature = results.Signature,
                        Type = results.Type,
                        Url = results.Uri.ToString(),
                        Version = Int32.Parse(results.Version),
                       Width=results.Width,
                        AppUserId = userId
                    };
                    _repo.AddPhotos(p);

                }
            }

            
            
        }



    }
}

Dating/Controllers/UsersController.cs
using AutoMapper;
using Dating.Data.Repositories;
using Dating.Helpers;
using Dating.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Dating.Controllers
{
    public class UsersController : Controller
    {
       
        private readonly IDatingRepository _repo;
        private readonly IMapper _mapper;
        public UsersController(IDatingRepository repository,IMapper mapper)
        {
            _repo = repository;
            _mapper = mapper;
        }
        // GET: Users
        public async Task<ActionResult> GetUsers(UserParams userParams)
        {
            var currentUserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
           
            var user = await _repo.GetUser(currentUserId);
            userParams.UserId = currentUserId;
            if (string.IsNullOrEmpty(userParams.Gender))
            {
                userParams.Gender = user.Gender == "male" ? "female" : "male";
            }
            var users = await _repo.GetUsers(userParams);
            var usersToReturn = _mapper.Map<IEnumerable<UsersListViewModel>>(users);

             Response.AddPagination(users.CurrentPage, users.PageSize, users.TotalItemsCount, users.TotalPages);

            ViewBag.CurrentPage = users.CurrentPage;
            ViewBag.TotalPages = users.TotalPages;
            ViewBag.TotalItems = users.TotalItemsCount;
            ViewBag.LastActive = users.OrderByDescending(l=>l.LastActive);
            ViewBag.Created = users.OrderByDescending(l=>l.Created);

            return View(usersToReturn);
        }

        // GET: Users/Details/5
        public async Task<ActionResult> GetUser(string id)
        {
            var user = await _repo.GetUser(id);
            var userToReturn = _mapper.Map<UserDetailesViewModel>(user);
            return View(userToReturn);
        }

       

        // GET: Users/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            var currentUserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            if (id!=currentUserId)
            {
                return StatusCode(401);
            }
            var user = await _repo.GetUser(id);
            var userToReturn = _mapper.Map<UserDetailesViewModel>(user);

            return View(userToReturn);
        }

        // POST: Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async  Task<ActionResult> Edit(UserDetailesViewModel model )
        {

            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
                 var user = await _repo.GetUser(model.Id);
                var currentUserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                if (user == null)
                    {
                        return NotFound();
                    }
                    else
                    {
                        if (currentUserId!=user.Id)
                        {
                            return StatusCode(401);
                        }
                user.Introduction = model.Introduction;
                user.LookingFor = model.LookingFor;
                user.Interests = model.Interests;
                user.City = model.City;
                user.Country = model.Country;
                await _repo.Update(user);
                         return RedirectToAction(nameof(GetUsers));
                        
                    }

               
            
         
        }
    }
}

Dating/Views/Users/Edit.cshtml
@model UserDetailesViewModel
@{
    ViewData["Title"] = "Edit";
}

<script src="jquery.timeago.js" type="text/javascript"></script>

<div class="row">
    <div class="col-sm-4">
        <h1>Your Profile:</h1>
    </div>
    <div class="col-sm-8">
        <div class="alert alert-info">
            <p class="lead"><strong>Information:</strong> You Have Made Change. Any Unsaved Changes Will Be Lost!</p>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-4">
        <div class="card">
            <div div class="card-img">
                <img class="img-fluid img-thumbnail m-2" src="@Model.PhotoUrl" alt="@Model.KnownAs" />
            </div>
            <div class="card-body">
                <div>
                    <strong>Location:</strong>
                    <p>@Model.Country, @Model.City</p>
                </div>
                <div>
                    <strong>Age:</strong>
                    <p>@Model.Age</p>
                </div>
                <div>
                    <strong>Last Active:</strong>
                    <p>@Model.LastSeen</p>
                </div>
                <div>
                    <strong>Member Since:</strong>
                    <p>@Model.Created.ToShortDateString()</p>
                </div>

            </div>

        </div>
    </div>
    <div class="col-md-8">

        <div class="card">

            <div class="card-header">
                <h4 class="card-title">Edit Ptofile Details</h4>
            </div>

            <form asp-action="Edit" asp-controller="Users" method="post">
                <div class="card-body m-2">
                    <div class="form-group row mb-3">
                        <h4>Description:</h4>
                        <textarea class="form-control col-sm-12" rows="6" asp-for="Introduction"></textarea>
                        <span asp-validation-for="Introduction" class="text-danger"></span>
                    </div>
                    <div class="form-group row mb-3">
                        <h4>Looking For:</h4>
                        <textarea class="form-control col-sm-12" rows="6" asp-for="LookingFor"></textarea>
                        <span asp-validation-for="LookingFor" class="text-danger"></span>
                    </div>
                    <div class="form-group row mb-3">
                        <h4>Interests:</h4>
                        <textarea class="form-control col-sm-12" rows="6" asp-for="Interests"></textarea>
                        <span asp-validation-for="Interests" class="text-danger"></span>
                    </div>

                    <hr />
                    <h4>Location Details:</h4>
                    <div class="form-group row">
                        <label asp-for="City" class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                            <input asp-for="City" class="form-control" />
                        </div>
                        <span asp-validation-for="City" class="text-danger"></span>
                    </div>
                    <div class="form-group row">
                        <label asp-for="Country" class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                            <input asp-for="Country" class="form-control" />
                        </div>
                        <span asp-validation-for="Country" class="text-danger"></span>
                    </div>
                </div>
                <div class="card-footer">
                    <button class="btn btn-success" type="submit">Save Changes</button>
                    <a class="btn btn-warning" asp-action="PhotosList" asp-controller="Photos" asp-route-userId="@Model.Id">Manage Photos</a>
                    <a class="btn btn-secondary" asp-area="Identity" asp-page="/Account/Manage/Index">Back to Profile setting</a>
                </div>
            </form>

        </div>


    </div>

</div>

Dating/Views/Users/GetUser.cshtml
@model UserDetailesViewModel
@{
    ViewData["Title"] = "GetUser";
}

<div class="row">
    <h1>@Model.KnownAs's Profile</h1>
</div>
<div class="row">
    <div class="col-sm-4">
        <div class="card">
            <div div class="card-img">
                <img class="img-fluid img-thumbnail m-2" src="@Model.PhotoUrl" alt="@Model.KnownAs" />
            </div> 
            <div class="card-body">
                <div>
                    <strong>Location:</strong>
                    <p>@Model.Country, @Model.City</p>
                </div>
                  <div>
                    <strong>Age:</strong>
                    <p>@Model.Age</p>
                </div>
                  <div>
                    <strong>Last Active:</strong>
                    <p>@Model.LastSeen</p>
                </div>
                <div>
                    <strong>Member Since:</strong>
                    <p>@Model.Created.ToShortDateString()</p>
                </div>

            </div>
            <div class="card-footer d-flex justify-content-center">
                <div class="btn-group-justified">
                   
                    <div class="btn-group">
                        <button class="btn btn-primary">Like</button>

                    </div>
                    <div class="btn-group">
                        <button class="btn btn-success">Message</button>
                    </div>
                      
                  
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-8">
        <div class="card">
            <div class="card-body m-2">
                <ul class="nav nav-tabs" id="myTab" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab"
                           aria-controls="home" aria-selected="true">About @Model.KnownAs</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="interests-tab" data-toggle="tab" href="#interests" role="tab"
                           aria-controls="interests" aria-selected="false">Interests</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="photos-tab" data-toggle="tab" href="#photos" role="tab"
                           aria-controls="photos" aria-selected="false">Photos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="messages-tab" data-toggle="tab" href="#messages" role="tab"
                           aria-controls="messages" aria-selected="false">Messages</a>
                    </li>
                </ul>
                
                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade show active mt-3" id="home" role="tabpanel" aria-labelledby="home-tab">
                        <h4>Description:</h4>
                        <p class="lead">@Model.Introduction</p>
                        <h4>Looking For:</h4>
                        <p class="lead">@Model.LookingFor</p>
                    </div>
                    <div class="tab-pane fade mt-3" id="interests" role="tabpanel" aria-labelledby="interests-tab">
                        <h4>Description:</h4>
                        <p class="lead">@Model.Interests</p>
                    </div>
                    <div class="tab-pane fade mt-4 ml-4" id="photos" role="tabpanel" aria-labelledby="photos-tab">
                       <p>
                            <div class="main-photo d-flex mb-5">
                              @foreach (var p in Model.Photos)
                              {
                                  if (p.IsMain)
                                  {
                                      <img asp-append-version="true" class="img-thumbnail d-block w-25 mb-2" src="@p.Url" alt="@Model.KnownAs" />
                                  }
                              }
                            </div>
                            <div id="carouselExampleIndicators" class="photos carousel slide mt-3" data-ride="carousel">
                                <ol class="carousel-indicators">
                                    @for (int i = 0; i < Model.Photos.Count; i++)
                                    {
                                        <li data-target="#carouselExampleIndicators" data-slide-to="[i]"></li>

                                    }

                                  
                                </ol>
                                <div class="carousel-inner">
                                    @foreach (var item in Model.Photos)
                                    {
                                        <div class="carousel-item active">
                                            <img src="@item.Url" class="d-block w-100" alt="...">
                                        </div>
                                    
                                    }

                                </div>
                                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Previous</span>
                                </a>
                                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </div>
                        </p>
                    </div>
                    <div class="tab-pane fade mt-3" id="messages" role="tabpanel" aria-labelledby="messages-tab">
                        <p class="lead">Message will go here</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Dating/Views/Users/GetUsers.cshtml
@model IEnumerable<UsersListViewModel>
@{
    ViewData["Title"] = "Get Users";
    string[] Genders = new string[] { "Male", "Female" };
}
<!-- header -->

<div class="text-center">
    <h2>Your matches - <span class="badge-info badge-pill">@ViewBag.TotalItems</span> found</h2>
</div>


<!-- HTML for filters -->

<div class="row">
    <form class="form-inline" novalidate>
        <div class="form-group row ">
            <label for="minAge" class="col-form-label">Age From:</label>
            <div class="col">
                <input type="number" class="form-control" style="width: 70px" id="minAge" name="minAge">
            </div>
        </div>

        <div class="form-group row ml-1">
            <label for="maxAge" class="col-form-label">Age To:</label>
            <div class="col">
                <input type="number" class="form-control" style="width: 70px" id="maxAge" name="maxAge">
            </div>
        </div>


        <div class="form-group row ml-1">
            <label for="gender" class="col-form-label">Show: </label>
            <div class="col">
                <select class="custom-select mr-sm-2" id="gender" name="gender">
                    <option value="">..Select Gender..</option>
                    @foreach (var g in @Genders)
                    {
                        <option value="@g">@g</option>
                    }
                </select>
            </div>
        </div>
        <button type="submit" class="btn btn-primary" style="margin-left:10px">Apply Filters</button>

    </form>
    <!-- HTML for ordering -->
    <div class="col pull-right">
        <label style="margin-right: 10px">Order By: </label>
        <div class="btn-group" role="group">
            <a class="btn btn-primary" asp-route-orderBy="lastActive">Last Active</a>
            <a class="btn btn-primary" asp-route-orderBy="created">Newest Members</a>
        </div>
    </div>
</div>
<br>




<div class="row justify-content-center">

    @foreach (var user in Model)
    {

        <partial name="Member" model="user" />
    }
</div>

<nav aria-label="Page navigation" class="mt-3">
    <ul class="pagination justify-content-center">
        <li class="page-item @(!(ViewBag.CurrentPage > 1) ? "disabled" : "")">
            <a asp-route-pageNumber="1" )"
               class="page-link">
                First Page
            </a>
        </li>
        <li class="page-item @(!(ViewBag.CurrentPage > 1) ? "disabled" : "")">
            <a asp-route-pageNumber="@(ViewBag.CurrentPage -1)"
               class="page-link">
                <<
            </a>
        </li>

        @for (int i = 1; i <= 3 && i <= ViewBag.TotalPages; i++)
        {
            <li class="page-item @((ViewBag.CurrentPage==i) ? "active" : "")">
                <a class="page-link" asp-route-pageNumber="@i">@i</a>
            </li>
        }

        <li class="page-item @(!(ViewBag.CurrentPage < ViewBag.TotalPages)? "disabled" :"")">
            <a class="page-link" asp-route-pageNumber="@(ViewBag.CurrentPage + 1)">>></a>
        </li>
        <li class="page-item @(!(ViewBag.CurrentPage < ViewBag.TotalPages)? "disabled" :"")">
            <a class="page-link" asp-route-pageNumber="@(ViewBag.TotalPages )">Last Page</a>
        </li>
    </ul>
</nav>

Dating/Views/Users/Member.cshtml
@model UsersListViewModel
 @{ 
     var photoUrl = Model.PhotoUrl ?? "~/images/user.png";
 }
<div class="card m-1 justify-content-center">
    <div class="card-body">
        <div class="card-img">
            <img src="@photoUrl" alt="@Model.KnownAs" class="img-fluid img-thumbnail" asp-append-version="true" width="130" height="150" />
            <ul class="list-inline text-center member-icons animate">
                <li class="list-inline-item"><a asp-action="GetUser" asp-controller="Users" asp-route-id="@Model.Id"
                                                class="btn btn-primary"><i class="fas fa-user"></i></a></li>
                <li class="list-inline-item"><button class="btn btn-primary"><i class="fas fa-heart"></i></button></li>
                <li class="list-inline-item"><button class="btn btn-primary"><i class="fas fa-envelope"></i></button></li>
            </ul>
        </div>
        <div class="text-center">
            <h5 class="card-text mt-1 mb-1"><i class="fas fa-user"></i> @Model.KnownAs, @Model.Age</h5>
        </div>
        <div class="text-center">
            <h5><small>@Model.City</small></h5>

        </div>
    </div>
</div>